name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we aren't using multiple versions but it's nice to have in one place so whatever
        java: [16]
      fail-fast: true
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Set Up Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.5.0

      - name: Build Mod
        run: ./gradlew build